ess-dmsc/h5cpp

src/h5cpp/property/file_creation.cpp
test/property/file_creation_test.cpp

So the current solution is to remove them from the build 
for 1.8
Update #151

These tests do not fail on 1.8

---

Jenkinsfile
src/h5cpp/file/file.cpp
src/h5cpp/file/file.hpp
src/h5cpp/file/functions.cpp
src/h5cpp/file/memory_driver.cpp
src/h5cpp/file/posix_driver.cpp
src/h5cpp/property/dataset_transfer.cpp
test/file/CMakeLists.txt
test/file/driver_test.cpp
test/file/file_open_test.cpp
test/file/file_test.cpp
test/file/is_hdf5_test.cpp
test/main.cpp
test/property/dataset_transfer_test.cpp

Test coverage for File classes, including Drivers and MPI-related code in the driver classes and in Dataset Transfer Proplists.
Jenkinsfile now builds on Docker images that support MPI, particularly the tests and coverage reports are run on one of these.

Test coverage for File classes, including Drivers and MPI-related stuff

---

src/h5cpp/error/descriptor.cpp
src/h5cpp/error/descriptor.hpp
src/h5cpp/error/error.cpp
src/h5cpp/error/error.hpp
src/h5cpp/error/h5c_error.cpp
test/CMakeLists.txt
test/error/CMakeLists.txt
test/error/descriptor_test.cpp
test/error/error_test.cpp
test/error/h5c_error_test.cpp
test/h5cpp_test_helpers.hpp

Better test coverage for the Error classes and, more importantly, some fundamental improvements.
There are problems to bring up with HDF group:
1) If `H5E_error2_t` could be made to initialize its C-string pointers as null. Would help avoid the problem of exceptions while in the error handling block. We do need to transfer those strings to `std::string`. I don't think that's unreasonable.
2) Getting messages for major and minor error numbers is itself prone to creating another error stack, in effect overwriting the existing one. This is as problem, because we do want to collect all the error information immediately, not at some later point. The way it is now is like shooting yourself in the foot.
3) No way to determine the state of the error auto-printing mechanism in the C-API without …

error classes improved, tests for error classes improved; updates #234'

---

src/h5cpp/node/group.cpp
src/h5cpp/node/group.hpp

It appears that it does not get used anywhere in the tests, possibly only in our programs that use it as a dependency. I think this ordering of parameters makes more sense, so all that remains is to refactor our code when we switch the package.

changed signature for create_dataset; updates #283'

---

cmake/BoostLibraryConfig.cmake
conanfile_desi.txt
conanfile_ess.txt
conanfile_ess_mpi.txt
src/h5cpp/core/path.cpp
test/datatype/string_test.cpp
test/node/dataset_test.cpp
test/property/chunk_cache_parameters_test.cpp
test/property/dataset_creation_test.cpp
test/property/object_copy_test.cpp

These changes reduce the boost dependence to only the `filesystem` module and use the bincrafters `boost_filesystem` conan package only.
This should help to solve the current problem with the h5cpp package not working on Windows as well as significantly decrease the size of the library. It also makes it much harder to inadvertently add dependence on other parts of boost.
Closes #233 
It requires adding the bincrafters conan repository as a remote, which may need adding to some documentation?
```
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
```

Bring in less boost

---

cmake/BoostLibraryConfig.cmake
conanfile_ess.txt
src/h5cpp/CMakeLists.txt

Fixes #326 
Changes link Boost::system and add as explicit dependency.

Fix Boost::system library not found problems

---

Jenkinsfile
conanfile_ess.txt
conanfile_ess_mpi.txt
src/h5cpp/core/path.cpp

Closes #288 
All Conan packages for dependencies now work on Windows. These changes reinstate the Windows build in the Jenkinsfile and uses Conan's virtualrunenv generator to ensure the shared libraries can be found.

Bring back Windows build on Jenkins

---

conanfile_ess.txt
conanfile_ess_mpi.txt

This is the version recommended by bincrafters and is more stable, as proven in my attempts to switch daquiri over to use bincrafters boost.

changed boost version in conan; updates #350'

---

Jenkinsfile

Closes #369 
Copies code from Jenkins node to build job containers instead of cloning from github every time.
Note, after merging these changes you'll need to hit the rebuild button on Jenkins for any PRs which are currently failing due to this issue.

Fix PR builds

---

src/h5cpp/datatype/type_trait.hpp
test/node/CMakeLists.txt
test/node/dataset_const_data.cpp

This pull request is a friendly reminder that the use of const is still not supported by h5cpp. Although I have for now fixed the problem in my code by adding 100 lines of code of TypeTrait specialisations it would be nice if I did not have to do that.
Closes #277

Extra type traits for using const

---

Jenkinsfile

Removing the slack notifier calls in the jenkinsfile as they're clogging up the slack channel.

Remove slack calls in jenkinsfile

---

src/h5cpp/core/windows.hpp

Fixed build (error C2371: 'ssize_t': redefinition;) for win32

fixed ssize_t redefined [win32]

---

src/h5cpp/file/direct_driver.cpp
src/h5cpp/file/driver.hpp
src/h5cpp/file/memory_driver.cpp
src/h5cpp/file/mpi_driver.cpp
src/h5cpp/file/posix_driver.cpp

In response to #392, and because I needed a project using Dlib and h5cpp, I have renamed the keywords. It is now compiling with Dlib.

renamed keywords for POSIX clashes

---

CMakeLists.txt
doc/source/users_guide/installing.rst

It updates the h5cpp version to 0.1.3 in `CMakeLists.txt` (to fix documentation)  and in `install.rst` to have recent debian packages  shown.

Issue 401: update version to 0.1.3

---

src/h5cpp/attribute/attribute_manager.cpp
src/h5cpp/core/object_handle.cpp
src/h5cpp/dataspace/dataspace.hpp
src/h5cpp/dataspace/selection_manager.cpp
src/h5cpp/property/creation_order.hpp
src/h5cpp/property/dataset_creation.cpp
src/h5cpp/property/property_class.cpp

The latest version of clang has improved compiler warnings. This causes problems when treating warnings as errors. I have thus fixed these warnings (plus a typo).

Fixed compiler warnings

---

conanfile_ess.txt
conanfile_ess_mpi.txt
src/h5cpp/filter/deflate.cpp
src/h5cpp/filter/fletcher32.cpp
src/h5cpp/filter/shuffle.cpp
src/h5cpp/property/creation_order.hpp

Turns out that there were a few more compiler warnings that needed addressing. This is that.

More compiler warning fixes

---

test/core/ObjectHandleDefault.cpp

By adding comma one can workaround
```
/home/jkotan/sources/h5cpp/test/core/ObjectHandleDefault.cpp:145:81: warning: ISO C++11 requires at least one argument for the "..." in a variadic macro
hdf5::ObjectHandle::Type::ERROR_STACK));
^
```
i.e. fix issue #422

fix for a warning with  INSTANTIATE_TEST_CASE_P

---

CMakeLists.txt
Jenkinsfile
conanfile_desi.txt
conanfile_ess.txt
conanfile_ess_mpi.txt
test/gtest_print.hpp

Closes #431
Added CMake option `DISABLE_TESTS` to disable building unit tests, which we don't need for example when building a conan package of the library.
Updated the Jenkinsfile to use our jenkins pipeline library, which simplifies the file quite a bit.
I've also fixed and enabled the CentOS and Mac builds which had been commented out.
I've also updated the gtest package used, which allows me to build successfully with gcc 9.2.
I'm not sure if #399 can be considered closed, but these changes should at least be a step in the right direction.

Add option to disable building unit tests and improve Jenkinsfile

---

test/gtest_print.hpp

it resolves #439 by defining LocalGTestColor enum

Issue 439: fixes the GTestColor problem for GTest < 1.10

---

src/h5cpp/dataspace/simple.cpp
src/h5cpp/datatype/array.cpp
src/h5cpp/datatype/compound.cpp
src/h5cpp/datatype/ebool.cpp
src/h5cpp/file/functions.hpp
src/h5cpp/node/dataset.cpp
src/h5cpp/property/dataset_creation.cpp
test/attribute/attribute_scalar_io_test.cpp
test/core/object_id_test.cpp
test/datatype/float_test.cpp
test/datatype/integer_test.cpp
test/datatype/string_test.cpp
test/error/error_test.cpp
test/node/dataset_direct_chunk_test.cpp
test/utilities/array_adapter_test.cpp

The PR resolves #460 by fixing the warning C4273 on windows by removing DLL_EXPORT from the `from_buffer` function.
It also fixes a couple of other warnings like, e.g.  warning C4267: '=': conversion from 'size_t' to 'unsigned short
except C4251 and C4275 which require to add more extern declaration so  it is better to place them in a separate PR.

Issue 460: fix for warning C4273 on windows

---

src/h5cpp/core/object_id.hpp
src/h5cpp/dataspace/points.hpp
src/h5cpp/error/descriptor.hpp
src/h5cpp/filter/external_filter.hpp
src/h5cpp/node/link.hpp
src/h5cpp/node/recursive_link_iterator.hpp
src/h5cpp/node/recursive_node_iterator.hpp
src/h5cpp/property/virtual_data_map.hpp

It resolves #466 by hiding C4251 windows warnings
With the PR the windows built looks more cleaner, i.e.
https://jenkins.esss.dk/dm/blue/organizations/jenkins/ess-dmsc%2Fh5cpp/detail/issue_466/1/pipeline/28

Issue 466: disable C4251 windows warnings

---

src/h5cpp/hdf5.hpp

It resolves #468 by including missing headers in hdf5.hpp

Issue 468: include missing headers in hdf5.hpp

---

src/h5cpp/filter/external_filter.cpp
src/h5cpp/filter/external_filter.hpp
src/h5cpp/node/dataset.cpp
src/h5cpp/node/dataset.hpp
test/filter/external_filter_test.cpp
test/node/dataset_direct_chunk_test.cpp
test/node/dataset_h5py_string_compat_test.cpp

It resolves #388 by adding `ExternalFilters` class and `Dataset::filters()` method and `ExternalFilter::name()` method
```c++
+    //!
+    //! \brief get the dataset external filters for the instance
+    //!
+    //! Returns an instance of the dataset external filters for the
+    //! dataset.
+    //!
+    //! \throws std::runtime_error in case of a failure
+    //! \return instance of ExternalFilters
+    //!
+    filter::ExternalFilters filters() const;
```
```c++
+    ExternalFilter(FilterID id,
+                   const std::vector<unsigned int> cd_values,
+                   const std::string &name=std::string());
+    ExternalFilter();
+    //!
+    //! \brief compression options
+    //!
+    //! Provides the external filter name
+    //!
+    //! \return filter name
+    //!
+ …
```

Issue 388: add ExternalFilters class and Dataset::filters() method 

---

src/h5cpp/datatype/float.cpp
src/h5cpp/datatype/float.hpp
src/h5cpp/datatype/integer.cpp
src/h5cpp/datatype/integer.hpp
src/h5cpp/datatype/type_trait.hpp
src/h5cpp/datatype/types.hpp
test/datatype/float_test.cpp
test/datatype/integer_test.cpp
test/datatype/string_test.cpp
test/node/dataset_h5py_string_compat_test.cpp

It resolves #434 by adding float16_t type and  missing datatype properties i.e.
- Integer -  precision, offset, order, pad
- Float -  precision, offset, order, pad, inpad, norm, ebias, fields
The properties `precision` and `offset` are very useful for NBit filter whille `fields` and `ebias` are used in creating of a new type examples i.e. `float16_t`.

Issue 434: add access for missing datatype properties and float16_t type

---

src/h5cpp/filter/CMakeLists.txt
src/h5cpp/filter/external_filter.cpp
src/h5cpp/filter/filter.cpp
src/h5cpp/filter/filter.hpp
src/h5cpp/filter/meson.build
src/h5cpp/filter/nbit.cpp
src/h5cpp/filter/nbit.hpp
src/h5cpp/filter/scaleoffset.cpp
src/h5cpp/filter/scaleoffset.hpp
src/h5cpp/filter/szip.cpp
src/h5cpp/filter/szip.hpp
src/h5cpp/hdf5.hpp
src/h5cpp/property/dataset_creation.cpp
src/h5cpp/property/dataset_creation.hpp
test/filter/CMakeLists.txt
test/filter/external_filter_test.cpp
test/filter/meson.build
test/filter/nbit_test.cpp
test/filter/scaleoffset_test.cpp
test/filter/szip_test.cpp

It resolves #389 by adding `NBit`, `SZip` and `ScaleOffset` filters.
It also add `Filter:is_encoding_enabled()` and `Filter:is_decoding_enabled()` as well as `DatasetCreationList::nfilters()`
to provide more information about filters for the user.

Issue 389: add NBit, SZip and ScaleOffset filters

---

src/h5cpp/filter/scaleoffset.hpp

It resolves #478 by changing `scale_factor_` to `scale_factor`

Issue 478: fix typo of scale_factor in ScaleOffset declaration

---

CMakeLists.txt
doc/CMakeLists.txt

Hi I was using this library with CMake's FetchContent
```
FetchContent_Declare(
h5cpp
GIT_REPOSITORY https://github.com/ess-dmsc/h5cpp
GIT_TAG origin/master)
FetchContent_MakeAvailable(h5cpp)
```
I found it useful to make the building of documentation optional, particularly because the `html` target conflicts with my own documentation target.

Optional docs

---

Jenkinsfile

This is a low priority change to move the user configuration for automated push to GitHub to the Jenkins shared library.

Use jenkins shared lib to setup Git user

---

src/h5cpp/file/functions.hpp
test/file/file_image_test.cpp

It resolves #494 by adding checks  for flags in `from_buffer(data, flags)`:  `DONT_COPY` without `DONT_RELEASE`

Issue 494: add checks for flags in from_buffer:  DONT_COPY without DONT_RELEASE

---

Jenkinsfile
src/h5cpp/file/functions.hpp
src/h5cpp/file/types.cpp
src/h5cpp/file/types.hpp
src/h5cpp/property/object_copy.cpp
src/h5cpp/property/object_copy.hpp
test/file/CMakeLists.txt
test/file/accessflags_test.cpp
test/file/imageflags_test.cpp
test/file/searchflags_test.cpp
test/property/object_copy_test.cpp

It resolves #497 by adding `&` operators for ImageFlags, SearchFlags, AccessFlags and CopyFlags.
Moreover, it fixes a typo in `operator|` of SearchFlags.

Issue 497: add and operators for ImageFlags, SearchFlags, AccessFlags and CopyFlags

---

doc/design/model.uml
doc/source/users_guide/dataspace.rst
src/h5cpp/datatype/types.cpp
src/h5cpp/datatype/types.hpp
test/datatype/type_test.cpp

In PR #521 I forgot to change Twos_Complement to TwosComplement (Correction to #503).

Issue 503b: change Twos_Complement to TwosComplement

---

src/h5cpp/dataspace/dataspace.cpp
src/h5cpp/dataspace/dataspace.hpp
test/dataspace/scalar_test.cpp

It resolves #507 by removing  `current_dimensions()` method for `Dataspace`. In order to get current dimensions one needs to use `Simple.current_dimensions()`

Issue 507: remove current_dimensions for Dataspace

---

doc/source/api_reference/namespace_dataspace.rst
doc/source/api_reference/namespace_datatype.rst
doc/source/api_reference/namespace_node.rst
doc/source/users_guide/overview.rst

It resolves rendering problems (#400) of the latest (master branch) documentation like
```
/home/jkotan/sources/h5cpp-build/doc/source/api_reference/namespace_datatype.rst:75: WARNING: Duplicate C++ declaration, also defined at api_reference/namespace_datatype:11.
Declaration is '.. cpp:class:: hdf5::datatype::Array : public hdf5::datatype::Datatype'.
/home/jkotan/sources/h5cpp-build/doc/source/api_reference/namespace_datatype.rst:87: WARNING: Duplicate C++ declaration, also defined at api_reference/namespace_datatype:11.
Declaration is '.. cpp:class:: hdf5::datatype::Compound : public hdf5::datatype::Datatype'.
/home/jkotan/sources/h5cpp-build/doc/source/api_reference/namespace_datatype.rst:93: WARNING: Duplicate C++ declaration, also defined at api_reference/namespace_datatype:11. …
```

Issue 400d: move documentation of enumerators to the end of sections

---

doc/source/advanced/cpp_datastructures.rst
doc/source/users_guide/dataspace.rst
examples/append_scalar_data.cpp
examples/append_vector_data.cpp
examples/mpi/writer_extend.cpp
examples/read_dataset.cpp
examples/swmr/swmr_builder.cpp
examples/write_vector_list.cpp
src/h5cpp/dataspace/simple.cpp
src/h5cpp/dataspace/simple.hpp
src/h5cpp/filter/szip.cpp
src/h5cpp/filter/szip.hpp
test/dataspace/simple_test.cpp
test/filter/szip_test.cpp
test/node/chunked_dataset_test.cpp
test/node/dataset_direct_chunk_test.cpp
test/node/dataset_extent_test.cpp
test/node/dataset_io_speed_test.cpp
test/node/dataset_partial_io_test.cpp

To avoid potential  interference with preprocessor  macros it would be good to change `static const` all-caps names to e.g. lower case names (similarly to #503) It resolves #528.  (If someone prefers camel than lower cases I can change to camel as well)

Issue 528: change all-caps names to lower case names

---

doc/source/_templates/CMakeLists.txt
doc/source/_templates/versions.html
doc/source/api_reference/namespace_datatype.rst
doc/source/conf.py.in
doc/source/index.rst.in

It resolves #535 by moving documentation versions links to the sidebar making use of sphinx templates. 
It also reorder datatype enumerators documentation to one block.
With the PR the visible documentation versions can be selected  in the `html_context.docs_versions` list defined in `conf.py.in`.

Issue 535: move documentation versions links to the sidebar

---

test/node/virtual_dataset_test.cpp

It resolves #522 by creating create gfcpl and gfapl test variables after  kFileCreate and kFileAccess are created

Issue 522: create gfcpl and gfapl after  kFileCreate and kFileAccess are created

---

test/property/link_access_test.cpp

It re-enables the windows link access tests mention in #249 by setting a proper windows path.

Issue 249: reenable windows link_access_test test

---

src/h5cpp/dataspace/hyperslab.cpp
src/h5cpp/dataspace/hyperslab.hpp
src/h5cpp/dataspace/points.cpp
src/h5cpp/dataspace/points.hpp
src/h5cpp/dataspace/selection.cpp
src/h5cpp/dataspace/selection.hpp
src/h5cpp/node/dataset.hpp
test/dataspace/hyperslab_simple_test.cpp
test/dataspace/points_simple_test.cpp

It resolves #221 by adding  virtual `type()`, `size()` and `dimensions()` methods to `Selection` class and implementing them in `Hyperslab` and `Points` classes.

Issue 221: add type(), size() and dimensions() to Selection class

---

Jenkinsfile

It resolves #546 by enabling macos tests back

Issue 546: enable macos tests

---

doc/source/api_reference/namespace_datatype.rst
doc/source/api_reference/namespace_filter.rst
doc/source/api_reference/namespace_property.rst
src/h5cpp/core/object_id.hpp
src/h5cpp/file/direct_driver.hpp
src/h5cpp/file/mpi_driver.hpp
src/h5cpp/file/types.hpp
src/h5cpp/node/dataset.hpp
src/h5cpp/node/group.hpp
src/h5cpp/property/dataset_access.hpp
src/h5cpp/property/dataset_creation.hpp
src/h5cpp/property/dataset_transfer.hpp
src/h5cpp/property/file_creation.hpp

It resolves #554 by adding an information to documentation for which version of hdf5 a class or a method is accessible

Issue 554: add an information to documentation for which version of hdf5 a class or a method is accessible

---

Jenkinsfile
conanfile_ess.txt
conanfile_macos.txt
doc/source/api_reference/CMakeLists.txt
doc/source/api_reference/index.rst
doc/source/api_reference/namespace_attribute.rst
doc/source/api_reference/namespace_dataspace.rst
doc/source/api_reference/namespace_datatype.rst
doc/source/api_reference/namespace_error.rst
doc/source/api_reference/namespace_file.rst
doc/source/api_reference/namespace_filter.rst
doc/source/api_reference/namespace_hdf5.rst
doc/source/api_reference/namespace_node.rst
doc/source/api_reference/namespace_property.rst
doc/source/conf.py.in
src/h5cpp/attribute/attribute_manager.hpp
src/h5cpp/core/object_id.hpp
src/h5cpp/core/path.hpp
src/h5cpp/core/version.hpp
src/h5cpp/datatype/datatype.hpp

It resolves #556 by add missing classes and functions to the sphinx API reference documentation.
It looks like in the current configuration doxygen/breathe/sphinx cannot link correctly `operator&`
```
/home/jenkins/build/doc/source/api_reference/namespace_file.rst:45: WARNING: doxygenfunction: Cannot find function "hdf5::file::operator&" in doxygen xml output for project "h5cpp" from directory: /home/jenkins/build/doc/source/../doxygen_xml
/home/jenkins/build/doc/source/api_reference/namespace_file.rst:47: WARNING: doxygenfunction: Cannot find function "hdf5::file::operator&" in doxygen xml output for project "h5cpp" from directory: /home/jenkins/build/doc/source/../doxygen_xml
/home/jenkins/build/doc/source/api_reference/namespace_file.rst:49: WARNING: doxygenfunction: Cannot find …
```

Issue 556: add missing classes and functions to the sphinx API reference documentation

---

doc/source/api_reference/namespace_filter.rst
doc/source/api_reference/namespace_hdf5.rst
src/h5cpp/core/object_handle.hpp
src/h5cpp/filter/scaleoffset.cpp
src/h5cpp/filter/scaleoffset.hpp
test/filter/scaleoffset_test.cpp

It resolves #558 by moving `SOScaleType` to `ScaleOffset::ScaleType`

Issue 558: move SOScaleType to ScaleOffset::ScaleType

---

doc/Doxyfile.in
doc/source/api_reference/namespace_filter.rst
src/h5cpp/file/types.cpp
src/h5cpp/filter/deflate.hpp
src/h5cpp/filter/scaleoffset.hpp
src/h5cpp/filter/shuffle.hpp
src/h5cpp/filter/szip.cpp
src/h5cpp/filter/szip.hpp
test/filter/szip_test.cpp

It resolves #560 by changing `static const unsigned` option masks to `OptionMask` enum.

Issue 560: change options_mask to OptionMask enum

---

Jenkinsfile
conanfile_macos.txt
src/h5cpp/node/dataset.cpp
src/h5cpp/property/dataset_transfer.cpp
test/node/dataset_extent_test.cpp

It resolves #568 by adding a fix for shrinking by Dataset.extent method.
It also removes ignoring of GCC warnings which is not needed anymore.

Issue 568: fix for shrinking by Dataset.extent method

---

README.md
doc/source/users_guide/installing.rst

It resolves #574 by updating cmake version in the documentation and add catch2

Issue 574: update requirements

---

.github/workflows/cmake-build.yml
conanfile.py
src/h5cpp/core/object_id.hpp

It resolves #586 by fixing the `H5O_info_t_`  definition for libhdf5 1.10.7

Issue 586: fix H5O_info_t_  definition

---

test/node/CMakeLists.txt

It resolves #595 by adding hdf5::hdf5_hl to test node link target for older libhdf5 e.g. 1.10.0

Issue 595: add hdf5::hdf5_hl to test node link target for older libhdf5 e.g. 1.10.0

---

.github/workflows/cmake-build.yml
conanfile.py
src/h5cpp/utilities/array_adapter.hpp
test/utilities/array_adapter_test.cpp

Array adapter unit test with potential fix

---

conanfile.py
src/h5cpp/core/utilities.hpp
test/node/dataset_io_speed_test.cpp

It resolves #611 by adding additional brackets to max function calls and renaming `max` to `dmax` in tests.

Issue 611: avoid interference with the windows max macro

---

README.md
conanfile.py

The DMSC Conan Artifactory server is being replaced, and is not needed for building h5cpp.
Closes #614.

Remove reference to ESS Conan Artifactory

---

Jenkinsfile
conanfile_ess.txt

Update HDF5 version in ESS conanfile

---

.github/workflows/cmake-build.yml

It resolves #642 by ugrading github test from debian/macos 11 to debian/macos 12

Issue #642: change debian11 to debian12

---

.github/workflows/cmake-build.yml
.github/workflows/conan/profiles/vs2019
src/h5cpp/core/iterator.hpp

Fixes build on macOS after compiler upgrade.

Issue 651: add include for ssize_t on clang 15

---

src/h5cpp/node/node.cpp
src/h5cpp/node/node.hpp

Fixes #659.
Nodes must first delete the handle to the underlying hdf5 resource before deleting their link.
Otherwise (i.e., link is deleted first), hdf5 attempts to close the file (if this was the last node referencing the file), which might fail (e.g., when using mpi-io, or close degree `Semi`) because the handle to the node would still be around.
I tried to add a test for this, but unfortunately the error message originates from the destructor of `ObjectHandle` catching any exception and only printing an error to stderr [here](https://github.com/ess-dmsc/h5cpp/blob/master/src/h5cpp/core/object_handle.cpp#L84-L93) without rethrowing to maintain `noexept`'ness and I could not find a sensible way to check what is printed to stderr within a catch2 test.

Destroy `Node`'s handle before its `Link`

---

src/h5cpp/attribute/attribute.cpp
src/h5cpp/attribute/attribute.hpp

As pointed out by @jkotan in [a comment](https://github.com/ess-dmsc/h5cpp/pull/660#issuecomment-2530695551) to the related PR #660, the same issue as described in #659 also appears for `Attribute`s:   
If an `Attribute` instance is kept around after the last reference to a file was dropped in client code, the order of `Attribute`'s members causes it to first try to close the underlying file before closing its own handle. If the file was opened with close degree `Semi` or the MPI-IO file driver was used, closing the file while the `Attribute` is still open is prohibited. 
This PR, therefore, applies the same fix to `Attribute` as was applied to `Node` in #660; that is, it reorders the member of `Attribute` to ensure that the handle is destroyed first, before attempting to close the file …

Destroy `Attributes'`s handle before its parent_link

---

.github/workflows/cmake-build.yml
src/h5cpp/attribute/attribute.hpp
src/h5cpp/node/dataset.hpp
test/attribute/attribute_variable_string_io.cpp
test/filter/external_filter_test.cpp
test/node/dataset_variable_string_io.cpp

Issue 666: fix for writing utf8 strings

---

CMakeLists.txt
README.md
doc/source/users_guide/installing.rst
ide/vscode/cmake-variants.yaml

Issue 671: set default H5CPP_WITH_BOOST to OFf

---

.github/workflows/cmake-build.yml
.github/workflows/debian13/Dockerfile
doc/source/users_guide/installing.rst

It resoves #684 by adding  documention and tests for debian 13

Issue 684: add documention and tests for debian 13
