- src/CMakeLists.txt
- src/attribute/attribute.cpp
- src/attribute/attribute_iterator.cpp
- src/attribute/attribute_manager.cpp
- src/dataspace/dataspace.cpp
- src/dataspace/scalar.cpp
- src/dataspace/selection.cpp
- src/dataspace/simple.cpp
- src/include/h5cpp/attribute/attribute.hpp
- src/include/h5cpp/attribute/attribute_manager.hpp
- src/include/h5cpp/dataspace/dataspace.hpp
- src/include/h5cpp/dataspace/selection.hpp
- src/include/h5cpp/dataspace/selection_manager.hpp
- src/include/h5cpp/dataspace/simple.hpp
- src/include/h5cpp/node/node.hpp
- src/node/node.cpp
- test/CMakeLists.txt
- test/attribute/CMakeLists.txt
- test/attribute/attribute_management_test.cpp
- test/attribute/attribute_name_access_test.cpp
- test/attribute/attribute_test.cpp
- test/attribute/attribute_test_fixtures.cpp
- test/attribute/attribute_test_fixtures.hpp
- test/dataspace/scalar_test.cpp
> Implemented basic attribute interface 

- src/CMakeLists.txt
- src/include/h5cpp/hdf5.hpp
- src/include/h5cpp/node/functions.hpp
- src/include/h5cpp/property/CMakeLists.txt
- src/include/h5cpp/property/object_copy_list.hpp
- src/node/functions.cpp
- src/property/object_copy_list.cpp
- test/property/CMakeLists.txt
- test/property/object_copy_list_test.cpp
> Solving Issue 25

- src/datatype/integer.cpp
- src/include/h5cpp/datatype/integer.hpp
- test/datatype/integer_test.cpp
This pull request implements the copy Dataset constructor for Integer types.
> Implemented Dataset copy constructor for Integer types

- test/datatype/float_test.cpp
- test/datatype/integer_test.cpp
> Re-definition error fix.

- test/CMakeLists.txt
> Removed examples from default test build

- src/h5cpp/hdf5.hpp
- src/h5cpp/node/CMakeLists.txt
- src/h5cpp/node/chunked_dataset.hpp
- src/h5cpp/node/functions.cpp
- src/h5cpp/node/link.cpp
- src/h5cpp/node/link.hpp
- src/h5cpp/node/link_iterator.cpp
- src/h5cpp/node/link_iterator.hpp
- src/h5cpp/node/link_view.cpp
- src/h5cpp/node/node_iterator.cpp
- src/h5cpp/node/node_iterator.hpp
- src/h5cpp/node/node_view.cpp
- src/h5cpp/node/recursive_link_iterator.cpp
- src/h5cpp/node/recursive_link_iterator.hpp
- src/h5cpp/node/recursive_node_iterator.cpp
- src/h5cpp/node/recursive_node_iterator.hpp
- src/h5cpp/node/virtual_dataset.hpp
- test/fixture.hpp
- test/node/CMakeLists.txt
- test/node/group_link_iteration_test.cpp
- test/node/group_node_iteration_test.cpp
- test/node/group_test_fixtures.cpp
- test/node/group_test_fixtures.hpp
- test/node/recursive_link_iterator_test.cpp
- test/node/recursive_node_iterator_test.cpp
- test/node/symbolic_link_creation_test.cpp
As both #113 and #114 are closely related pull request solves both of them. The iterators are fairly simple to use. Though we do not have a special view object for them to use them in a for each construction, however, for all other STL interfaces the provided factory functions will do well.
Update #113 
Update #114
> Issue 114 and 113

- src/h5cpp/attribute/attribute_manager.cpp
- src/h5cpp/attribute/attribute_manager.hpp
- test/attribute/attribute_test.cpp
This function allows to easily add new attribute with values.
However, for simple reading we first have to review the entire
IO and type trait code.
Update #147
> Added create_from function for AttributeManager

- cmake/PackageConfig.cmake
Should solve the version problem in the CMake package.
> Fixed name of the package version file

- h5cpp-config.cmake
- src/h5cpp/CMakeLists.txt
> The fix seems to do the job. Give it a try

- src/h5cpp/attribute/attribute.cpp
- src/h5cpp/attribute/attribute.hpp
- test/attribute/attribute_test.cpp
> Added close function and hid_t conversion operator

- src/h5cpp/node/group.hpp
- src/h5cpp/node/node.cpp
- src/h5cpp/node/node.hpp
- test/node/group_test.cpp
This should close the referenced tickets. 
Update #192
Update #217
> Added close() method to the Node class

- CMakeLists.txt
> Fixed typo.

- src/h5cpp/core/version.cpp
- src/h5cpp/core/version.hpp
- test/core/version_test.cpp
This should basically close issue 253
> Refactured accessor methods for the version numbers

- test/node/link_target_test.cpp
> Fixed boost path issue.

- test/CMakeLists.txt
> Add Boost libraries to unit_tests executable target

- src/h5cpp/core/object_handle.cpp
- src/h5cpp/core/object_handle.hpp
- src/h5cpp/core/object_id.cpp
- src/h5cpp/core/object_id.hpp
- src/h5cpp/core/version.cpp
- test/core/ObjectHandleDefault.cpp
- test/core/object_handle_test.cpp
- test/core/object_id_test.cpp
- test/core/version_test.cpp
One thing still obviously missing is comprehensive tests for `PROPERTY_LIST_CLASS`
> version, id and handle tests improved; updates #86'

- README.md
Closes #329 
Adds details on Conan, including how to disable it if using system-installed libraries.
> Update build information in readme

- README.md
Make the documentation pages more obvious with a badge.
> Add a badge link to documentation

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/Readme.md
- examples/append_scalar_data.cpp
- examples/append_vector_data.cpp
- examples/attributes/CMakeLists.txt
- examples/attributes/attribute_creation.cpp
- examples/attributes/attribute_io.cpp
- examples/attributes/attribute_iteration.cpp
- examples/basic_files.cpp
- examples/complex.hpp
- examples/complex_io.cpp
- examples/rgbpixel_h5.hpp
- examples/std_vector_io.cpp
- examples/swmr/swmr_builder.cpp
- examples/vector.hpp
- examples/vector_h5.hpp
- examples/write_single_vector.cpp
- examples/write_vector_list.cpp
I have done some minor improvements to one of the examples. It is possible that I will make more improvements over the coming week or so. I will collect these improvements in this pull request. Thus, if you decide to do a merge, please do not delete the branch.
See issue #241
> Improve examples (Issue #241)

- h5cpp-config.cmake.in
> Add Boost system as a CMake dependency

- examples/CMakeLists.txt
- examples/read_dataset.cpp
I created a much needed example on how to read data and metadata from a dataset.
The example does not actually build on my machine due to at least two different problems with the CMake code but it does when compiled in another project.
References #361
> Add example for reading datasets and information about datasets

- src/h5cpp/dataspace/simple.cpp
- src/h5cpp/dataspace/simple.hpp
The code should be pretty self explanatory.
Closes #363
> Fix problem with static member variable

- src/h5cpp/dataspace/points.hpp
- test/dataspace/points_simple_test.cpp
It seems that all rank situations are tested. We can thus close this
ticket.
Update #344
> Added more documentation

- CMakeLists.txt
> Fixed version number in the root CMakeLists.txt

- src/h5cpp/file/direct_driver.cpp
- test/file/driver_test.cpp
It resolves #408 by adding missing file_access include.
> Fix compilation error of DirectDriver

- test/node/dataset_direct_chunk_test.cpp
It fixes typo im direct chunk tests
> Issue 286: fix direct chunk deflate tests

- doc/source/users_guide/installing.rst
- test/node/dataset_direct_chunk_test.cpp
It updates information how to install h5cpp library from debian packages by adding debian focal
> add ubuntu focal to install on debian documentation 

- src/h5cpp/core/CMakeLists.txt
> Add missing header file to install step.

- src/h5cpp/attribute/attribute_manager.cpp
- src/h5cpp/core/object_handle.cpp
- src/h5cpp/core/object_handle.hpp
- src/h5cpp/core/object_id.cpp
- src/h5cpp/core/object_id.hpp
- src/h5cpp/node/node.cpp
My take to fix #451.  Please review in particluar the last commit since it seems to leave the ObjectId class essentially empty...
> HDF compatibility fixes

- Jenkinsfile
- doc/source/conf.py.in
Move documentation publishing steps in Jenkinsfile to Debian node.
> Fix Jenkins hanging build by removing Fedora node usage

- src/h5cpp/file/types.cpp
- src/h5cpp/file/types.hpp
- test/file/file_image_test.cpp
It resolves #488 by adding << and | operators for ImageFlags
> Issue 488: add << and | operators for ImageFlags

- src/h5cpp/file/functions.hpp
- test/file/file_image_test.cpp
It resolves #491 by adding  from_buffer with const data
> Issue_491: add from_buffer with const data

- src/h5cpp/attribute/attribute.hpp
- src/h5cpp/attribute/attribute_manager.hpp
- src/h5cpp/dataspace/type_trait.hpp
- src/h5cpp/datatype/enum.hpp
- src/h5cpp/datatype/factory.hpp
- src/h5cpp/hdf5.hpp
- src/h5cpp/node/dataset.hpp
- test/datatype/enum_test.cpp
- test/datatype/float_test.cpp
- test/datatype/integer_test.cpp
It resolves #519 by adding back const versions of Dataset.write and Dataset.read removed in #515
> Issue 519: add back const version of Dataset.write and Dataset.read

- src/h5cpp/node/dataset.hpp
It resolves #523 by using  file datatype to read strings
> Issue 523: use file datatype to read strings

- Jenkinsfile
The condition for  for finding docs_* branches needs to be fixed.
> Issue 400c: fix condition for finding docs_* branches

- doc/source/users_guide/installing.rst
It resolves #537 by updating installation documentation
> Issue 537: update keyring command in the installing.rst

- Jenkinsfile
It resolves #539 by fixing location of doxygen documentation
> Issue 539: update link for documentation created by doxygen

- src/h5cpp/CMakeLists.txt
It resolves #502 by changing cmake generators to "if" statements which are resolved during cmake configuration
> Issue 502: change cmake generators to "if" statements

- cmake/Sphinx.cmake
- src/h5cpp/node/group.cpp
- src/h5cpp/node/group.hpp
- test/node/group_test.cpp
It resolves #549 by adding implementation of `Group::flush()`
> Issue 549: add Group::flush()

- doc/Doxyfile.in
- doc/source/api_reference/namespace_file.rst
- doc/source/users_guide/overview.rst
- src/h5cpp/core/object_id.hpp
- src/h5cpp/file/direct_driver.hpp
- src/h5cpp/file/mpi_driver.hpp
- src/h5cpp/file/types.hpp
- src/h5cpp/hdf5.hpp
- src/h5cpp/node/dataset.hpp
- src/h5cpp/node/group.hpp
- src/h5cpp/property/dataset_access.hpp
- src/h5cpp/property/dataset_creation.hpp
- src/h5cpp/property/dataset_transfer.hpp
- src/h5cpp/property/file_creation.hpp
It resolves #552 by using the predefined \_DOXYGEN\_ variable
> Issue 552: add predefined _DOXYGEN_ variable

- .github/workflows/cmake-build.yml
> Enable GitHub CI builds for all branches

- .github/workflows/cmake-build.yml
It resolves #576 by updating github test labels
> Issue 576: update github test labels

- src/h5cpp/dataspace/CMakeLists.txt
- src/h5cpp/dataspace/meson.build
- src/h5cpp/dataspace/pool.cpp
- src/h5cpp/dataspace/pool.hpp
- test/dataspace/CMakeLists.txt
- test/dataspace/meson.build
- test/dataspace/pool_test.cpp
- test/datatype/vlen_array_test.cpp
It resolves #579 by extending  DatasetPool to support arbitrary Simple dataspaces
> Issue 579: extend DatasetPool to arbitrary Simple dataspaces

- examples/append_vector_data.cpp
- examples/attributes/attribute_io.cpp
- examples/complex_io.cpp
- examples/read_dataset.cpp
- examples/std_vector_io.cpp
- examples/swmr/swmr_reader.cpp
- examples/write_read_vector.cpp
- src/h5cpp/CMakeLists.txt
- src/h5cpp/h5cpp.hpp
- src/h5cpp/nexus.hpp
It resolves #581 by adding h5cpp.hpp and nexus.hpp headers
> Issue 581: add h5cpp.hpp and nexus.hpp headers

- doc/CMakeLists.txt
- doc/Doxyfile.in
- doc/doxygen-bizflat.css
It resolves #583 by changing colors of doxygen API documentation to the ones used in sphinx
> Issue 583: change colors of doxygen API documentation

- src/h5cpp/property/file_access.cpp
- src/h5cpp/property/file_access.hpp
> change names of parameters of library_version_bounds

- Jenkinsfile
- README.md
This is now automated in the Jenkins shared library. Also update ESS Jenkins build nodes and fix name in README.
> Remove local conan server config

- conanfile.py
- src/h5cpp/core/object_handle.cpp
- src/h5cpp/file/file.hpp
- src/h5cpp/node/dataset.cpp
- src/h5cpp/node/dataset.hpp
- test/error/descriptor_test.cpp
It resolves #621 by adding support for 1.14.0
> Issue 621: add support for hdf5 1.14.0

- README.md
> Remove bincrafters config from README

- src/h5cpp/node/node_iterator.hpp
> Make NodeIterator range-conform by adding a default ctor

- src/h5cpp/file/driver.hpp
- test/file/driver_test.cpp
It resolves #650 by adding `DriverID::Custom = 0`
> Issue 650: add Custom to DriverID enum

- .github/workflows/cmake-build.yml
- .github/workflows/debian11/Dockerfile
- CMakeLists.txt
- cmake/FindHDF5.cmake
- cmake/HDF5LibraryConfig.cmake
> Issue 677: add cmake/FindHDF5.cmake back
